name: todo_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^5.3.0
  flutter_bloc: ^8.1.2


  # Others
  equatable: ^2.0.5
  get_it: ^7.6.7
  bloc: ^8.1.0

  gap: ^3.0.1
  floor: ^1.4.2
  intl: ^0.19.0


  go_router: ^14.2.3
  injectable: ^2.3.2
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.2
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  flutter_alice: ^1.1.1
  firebase_analytics: ^11.3.0
  uuid: ^4.5.0
  workmanager: ^0.5.2
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.0
  flutter_easyloading: ^3.0.5
  another_flushbar: ^1.12.30





dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true


  assets:
    - assets/icons/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
