// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/*class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYcscfqh_LoVjK8M8JqBIyLJtF10pq-rU',
    appId: '1:167763629226:android:f75c76415d37f22cbbacd3',
    messagingSenderId: '298096462225',
    projectId: 'todoapp-e06fa',
    storageBucket: 'todoapp-e06fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenPQ3ggZNfdFKoEZwuiBnSBKx5sYuPiQ',
    appId: '1:167763629226:ios:8a04e26673c102d7bbacd3',
    messagingSenderId: '167763629226',
    projectId: 'ready-to-learn-edb1e',
    storageBucket: 'todoapp-e06fa.appspot.com',
    iosBundleId: 'com.flutter.todoApp',
  );


}*/


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _getAndroidOptions();
      case TargetPlatform.iOS:
        return _getIOSOptions();
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _getAndroidOptions() {
    if (const String.fromEnvironment('FLAVOR') == 'staging') {
      return androidStaging;
    } else {
      return androidLive;
    }
  }

  static FirebaseOptions _getIOSOptions() {
    if (const String.fromEnvironment('FLAVOR') == 'staging') {
      return iosStaging;
    } else {
      return iosLive;
    }
  }

  static const FirebaseOptions androidLive = FirebaseOptions(
    apiKey: 'AIzaSyCYcscfqh_LoVjK8M8JqBIyLJtF10pq-rU',
    appId: '1:167763629226:android:f75c76415d37f22cbbacd3',
    messagingSenderId: '298096462225',
    projectId: 'todoapp-e06fa',
    storageBucket: 'todoapp-e06fa.appspot.com',
  );

  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: 'AIzaSyCYcscfqh_LoVjK8M8JqBIyLJtF10pq-rU',
    appId: '1:167763629226:android:fb335dd6c6d484e3bbacd3',
    messagingSenderId: '298096462225',
    projectId: 'todoapp-e06fa',
    storageBucket: 'todoapp-e06fa.appspot.com',
  );

  static const FirebaseOptions iosLive = FirebaseOptions(
    apiKey: 'AIzaSyBenPQ3ggZNfdFKoEZwuiBnSBKx5sYuPiQ',
    appId: '1:167763629226:ios:8a04e26673c102d7bbacd3',
    messagingSenderId: '167763629226',
    projectId: 'ready-to-learn-edb1e',
    storageBucket: 'todoapp-e06fa.appspot.com',
    iosBundleId: 'com.flutter.todoApp',
  );

  static const FirebaseOptions iosStaging = FirebaseOptions(
    apiKey: 'AIzaSyBenPQ3ggZNfdFKoEZwuiBnSBKx5sYuPiQ',
    appId: '1:167763629226:ios:8a04e26673c102d7bbacd3',
    messagingSenderId: '167763629226',
    projectId: 'STAGING_PROJECT_ID',
    storageBucket: 'STAGING_STORAGE_BUCKET',
    iosBundleId: 'com.yourcompany.stagingApp',
  );
}

