// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMwzvCrkvtVPYofaPunsUZ4GMfhE29vA',
    appId: '1:298096462225:web:37220ea4868e4146b2f230',
    messagingSenderId: '298096462225',
    projectId: 'ready-to-learn-edb1e',
    authDomain: 'ready-to-learn-edb1e.firebaseapp.com',
    storageBucket: 'ready-to-learn-edb1e.appspot.com',
    measurementId: 'G-WHX7LL9HCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYcscfqh_LoVjK8M8JqBIyLJtF10pq-rU',
    appId: '1:167763629226:android:f75c76415d37f22cbbacd3',
    messagingSenderId: '298096462225',
    projectId: 'todoapp-e06fa',
    storageBucket: 'todoapp-e06fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4HDLst74Wf_HnjqQPV_L3kmKOAWBRUjM',
    appId: '1:298096462225:ios:c0235aa4bd181b4eb2f230',
    messagingSenderId: '298096462225',
    projectId: 'ready-to-learn-edb1e',
    storageBucket: 'ready-to-learn-edb1e.appspot.com',
    iosBundleId: 'com.pointsafetynor.readytolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4HDLst74Wf_HnjqQPV_L3kmKOAWBRUjM',
    appId: '1:298096462225:ios:b7ee9cf9fec76cc8b2f230',
    messagingSenderId: '298096462225',
    projectId: 'ready-to-learn-edb1e',
    storageBucket: 'ready-to-learn-edb1e.appspot.com',
    iosBundleId: 'com.pointsafetynor.readytolearn.RunnerTests',
  );
}
